# Generated by Django 6.1 on 2026-09-08 11:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=32,
                    ),
                ),
                ("nationality", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=32)),
                ("address_line", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state_region", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "passport_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="applicants/photos/"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="admissions__email_c5ea68_idx"),
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="admissions__last_na_248e2c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application_number",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("waitlisted", "Waitlisted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("diploma", "Diploma"),
                            ("undergraduate", "Undergraduate"),
                            ("postgraduate", "Postgraduate"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("institution", models.CharField(max_length=255)),
                ("current_level", models.CharField(blank=True, max_length=100)),
                ("previous_computer_training", models.BooleanField(default=False)),
                ("training_description", models.TextField(blank=True)),
                ("preferred_start_date", models.DateField(blank=True, null=True)),
                (
                    "preferred_session",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                        ],
                        max_length=16,
                    ),
                ),
                ("has_computer_access", models.BooleanField(default=False)),
                ("reason_for_joining", models.TextField(blank=True)),
                (
                    "referral_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("friend_family", "Friend or family"),
                            ("social_media", "Social media"),
                            ("search", "Web search"),
                            ("event", "Event or fair"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("declaration_accepted", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applicant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application",
                        to="admissions.applicant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("relationship", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=32)),
                ("alt_phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contact",
                        to="admissions.application",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("relationship", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian",
                        to="admissions.application",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegistrationCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course_ref", models.PositiveIntegerField(blank=True, null=True)),
                ("course_name", models.CharField(max_length=255)),
                (
                    "fee_at_registration",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="admissions.application",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["status", "created_at"], name="admissions__status_bb96e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["application_number"], name="admissions__applica_7574f8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationcourse",
            constraint=models.UniqueConstraint(
                fields=("application", "course_ref"), name="uniq_course_per_application"
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationcourse",
            constraint=models.CheckConstraint(
                condition=models.Q(("fee_at_registration__gte", 0)),
                name="registrationcourse_fee_non_negative",
            ),
        ),
    ]
