# Generated by Django 6.1 on 2026-09-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=32)),
                ("year", models.PositiveIntegerField()),
                ("value", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "year"), name="uniq_sequence_scope_year"
                    )
                ],
            },
        ),
    ]
